### ISSUE TITLE
Images changing on hover

### ISSUE THREAD

**Issue by PierreLeMaguer** [magefan/module-lazyload#17]
Hello,

I'm using the last version of the module.
Magento CE 2.3.3.

i'm using the following HTML to show a different image on hover.
`
<a href="https://www.youtube.com/user/LaMaisonDuCanevas" class="youtube social-link">
            <img src="https://preprod.canevas.com/pub/static/version1584693125/frontend/Lmc/default/fr_FR/images/cms/footer/ytube.png" data-original="https://preprod.canevas.com/pub/static/version1584693125/frontend/Lmc/default/fr_FR/images/cms/footer/ytube.png" alt="" class="loaded" data-was-processed="true">
            <img src="https://preprod.canevas.com/pub/static/version1584693125/frontend/Lmc/default/fr_FR/Magefan_LazyLoad/images/pixel.jpg" data-original="https://preprod.canevas.com/pub/static/version1584693125/frontend/Lmc/default/fr_FR/images/cms/footer/ytube_hover.png" class="_active" alt="">
        </a>
`
The first image is displayed initially and the second one is not displayed (display: none).
The issue is that, the src of the second image which appears on hover is still the pixel url. It does not change for the data original one.

Thanks,
Pierre

**Comment by ihorvansach** [comment]
@PierreLeMaguer , what I can suggest is to improve JavaScript that makes hover (hide one and display another image), and once it shows the second image, then replace src with the value from data-original. Idea how to do this you can check here
https://github.com/magefan/module-lazyload/blob/master/view/frontend/templates/lazy.phtml
https://prnt.sc/rme03e

**Comment by PierreLeMaguer** [comment]
Thanks for your answer !
