### ISSUE TITLE
Lazyload Megamenu Images

### ISSUE THREAD

**Issue by mindfriction** [magefan/module-lazyload#18]
First, thanks for your great plugin!

I need apply lazyload on the images inside a mega menu that is in the header. 
The images in mega menu are not seen unless "hovering" over a particular category in the menu. Also, the mega menu is above the fold and doesn't need scrolling down the page which presents another challenge. 

Is there a way to implement lazyload for a menu that is in header (doesn't need scroll) and has images within menu that shall be displayed after triggering a “hover” state.

This scenario is sort of similar to product page tabs, where the images are lazyloaded and generated/displayed not after scrolling down the page to that section, but only after opening the particular tab. 

Thanks!

**Comment by ihorvansach** [comment]
@mindfriction , you can implement the similar for the menu as for product tabs, please check this code
https://github.com/magefan/module-lazyload/blob/master/view/frontend/templates/lazy.phtml
https://prnt.sc/rme03e

So once the menu is open, replace all pixel images with the original image

**Comment by mindfriction** [comment]
Hi @ihorvansach that worked! thank you!
