### ISSUE TITLE
error when install with Magento 2.4.6

### ISSUE THREAD

**Issue by joomlacorner** [magefan/module-lazyload#38]
When install with Magento 2.4.6 will got this message when setup:upgrade.
call_user_func(): Argument #1 ($callback) must be a valid callback, class "Magefan\LazyLoad\Setup\Patch\Data\ConvertConfigToJsonPatch" not found#0

**Comment by magefan** [comment]
@joomlacorner , could you please check if file
app/code/Magefan/LazyLoad/Setup/Patch/Data/ConvertConfigToJsonPatch.php
or
vendor/magefan/module-lazy/Setup/Patch/Data/ConvertConfigToJsonPatch.php

exits on your server
