### ISSUE TITLE
Missing required argument $skipBlocks of Magefan\\LazyLoad\\Plugin\\BlockPlugin.

### ISSUE THREAD

**Issue by premamdckap** [magefan/module-lazyload#44]
We are facing the following exception in the checkout(Magento version: 2.4.5-p1),

{"0":"Missing required argument $skipBlocks of Magefan\\LazyLoad\\Plugin\\BlockPlugin.","1":"#1 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:34]\n#2 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:59]\n#3 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]\n#4 Magento\\Framework\\ObjectManager\\ObjectManager->get() called at [vendor\/magento\/framework\/Interception\/PluginList\/PluginList.php:174]\n#5 Magento\\Framework\\Interception\\PluginList\\PluginList->getPlugin() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:144]\n#6 Magento\\Cms\\Block\\Block\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#7 Magento\\Cms\\Block\\Block\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Cms\/Block\/Block\/Interceptor.php:230]\n#8 Magento\\Cms\\Block\\Block\\Interceptor->toHtml() called at [pub\/errors\/default\/503.phtml:24]\n#9 require_once() called at [pub\/errors\/default\/page.phtml:22]\n#10 require_once() called at [pub\/errors\/processor.php:437]\n#11 Magento\\Framework\\Error\\Processor->_renderPage() called at [pub\/errors\/processor.php:231]\n#12 Magento\\Framework\\Error\\Processor->process503() called at [pub\/errors\/503.php:11]\n#13 require() called at [vendor\/magento\/framework\/Session\/SaveHandler\/Redis.php:100]\n#14 Magento\\Framework\\Session\\SaveHandler\\Redis->read() called at [vendor\/magento\/framework\/Session\/SaveHandler.php:212]\n#15 Magento\\Framework\\Session\\SaveHandler->callSafely() called at [vendor\/magento\/framework\/Session\/SaveHandler.php:125]\n#16 Magento\\Framework\\Session\\SaveHandler->read()\n#17 session_start() called at [vendor\/magento\/framework\/Session\/SessionManager.php:186]\n#18 Magento\\Framework\\Session\\SessionManager->start() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#19 Magento\\Framework\\Session\\Generic\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#20 Magento\\Framework\\Session\\Generic\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#21 Magento\\Framework\\Session\\Generic\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/Session\/Generic\/Interceptor.php:41]\n#22 Magento\\Framework\\Session\\Generic\\Interceptor->start() called at [vendor\/magento\/framework\/Session\/SessionManager.php:123]\n#23 Magento\\Framework\\Session\\SessionManager->__construct() called at [generated\/code\/Magento\/Framework\/Session\/Generic\/Interceptor.php:14]\n#24 Magento\\Framework\\Session\\Generic\\Interceptor->__construct() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:121]\n#25 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:66]\n#26 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]\n#27 Magento\\Framework\\ObjectManager\\ObjectManager->get() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:170]\n#28 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:276]\n#29 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->getResolvedArgument() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:239]\n#30 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:34]\n#31 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:59]\n#32 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]\n#33 Magento\\Framework\\ObjectManager\\ObjectManager->get() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:170]\n#34 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:276]\n#35 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->getResolvedArgument() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:239]\n#36 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:34]\n#37 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:59]\n#38 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]\n#39 Magento\\Framework\\ObjectManager\\ObjectManager->get() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:170]\n#40 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:276]\n#41 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->getResolvedArgument() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:239]\n#42 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:34]\n#43 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:59]\n#44 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]\n#45 Magento\\Framework\\ObjectManager\\ObjectManager->get() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:206]\n#46 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->parseArray() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:182]\n#47 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:276]\n#48 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->getResolvedArgument() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:239]\n#49 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:34]\n#50 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:59]\n#51 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]\n#52 Magento\\Framework\\ObjectManager\\ObjectManager->get() called at [vendor\/magento\/framework\/App\/FrontController.php:109]\n#53 Magento\\Framework\\App\\FrontController->__construct() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:14]\n#54 Magento\\Framework\\App\\FrontController\\Interceptor->__construct() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:121]\n#55 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:66]\n#56 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]\n#57 Magento\\Framework\\ObjectManager\\ObjectManager->get() called at [vendor\/magento\/framework\/App\/Http.php:115]\n#58 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:23]\n#59 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:264]\n#60 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:30]\n","url":"\/inventory_catalog\/product\/getQty\/?sku=94741-750-AI&channel=website&salesChannelCode=base&_=1714961102632","script_name":"\/index.php","report_id":"f10d1f4e031a3ae2ebf3479ca17cb88e990cdad79f9a3aca8b0d1292b4f91604"}

**Comment by magefan** [comment]
@premamdckap , could you please run the command
bin/magento setup:di:compile

Let us know if it helps.
