### ISSUE TITLE
No space between attributes

### ISSUE THREAD

**Issue by simonrl** [magefan/module-lazyload#5]
Error thrown on validator.w3.org and caused in `Magefan\LazyLoad\Plugin\BlockPlugin`, L80-81:

"data-original" gets added directly after the src attribute, resulting in no space between the two IMG attributes.

Expected:
`<img src="..." data-original="..." />`

Actual result:
`<img src="..."data-original="..." />`

(note the missing space)

Would you release a new version if I create a PR? We're using the module via composer, so it would be nice to have that fix in the code.

Thanks
Simon

**Comment by magefan** [comment]
@simonrl , thank you for your report. PR request will be greate. Tnx.

**Comment by magefan** [comment]
Hello @simonrl , did you have a chance to create a PR, if you have a fix you can simply send it to support@magefan.com we will review it and add to the repo.

**Comment by simonrl** [comment]
Hey, sorry, completely forgot that. See here pls: https://github.com/magefan/module-lazyload/pull/8
